#train_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/vox3s100ps/training.csv"
#validation_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/vox3s100ps/validation.csv"
#test_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/vox3s100ps/testing.csv"
train_data_dir: "/home/ilaydaecetemir/training.csv"
validation_data_dir: "/home/ilaydaecetemir/validation.csv"
test_data_dir: "/home/ilaydaecetemir/vox2s/testing.csv"

#batch_size: 128
batch_size: 64

learning_rate: 0.001
num_epochs: 50

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
#input_shape: [129, 500, 1]
#input_shape: [129, 100, 1]
input_shape: [129, 100, 1]

#model: "inceptionv3_crnn" # _finetune"
model: "topcoder_crnn_finetune"
#model: "topcoder_5s_finetune"


#segment_length: 10  # number of seconds each spectogram represents   
#segment_length: 2
segment_length : 2
pixel_per_second: 50

label_names: ["NL", "EN"]
num_classes: 2

#label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
#num_classes: 6




