train_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/voxforge100_2s/training.csv"
validation_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/voxforge100_2s/validation.csv"
test_data_dir: "/mnt/d/Documents/VU/thesis/crnn-lid-master/data/voxforge100_2s/testing.csv"

#batch_size: 128
batch_size: 64

learning_rate: 0.001
num_epochs: 50

data_loader: "ImageLoader"
color_mode: "L"  # L = bw or RGB
#input_shape: [129, 500, 1]
#input_shape: [129, 100, 1]
input_shape: [129, 200, 1]

model: "inceptionv3_crnn" # _finetune"
#model: "topcoder_crnn_finetune"

#segment_length: 10  # number of seconds each spectogram represents   
#segment_length: 2
segment_length : 1
pixel_per_second: 100

label_names: ["NL", "EN"]
num_classes: 2

# label_names: ["EN", "DE", "FR", "ES", "CN", "RUS"]
# num_classes: 6




